"""Initial migration

Revision ID: e33a07b550bf
Revises: 
Create Date: 2025-01-19 22:39:08.814322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33a07b550bf'
down_revision = None
branch_labels = None
depends_on = None


def data_upgrades():
    """Add any optional data upgrade migrations here!"""

    products = sa.sql.table(
        'products',
        sa.sql.column('id', sa.Integer),
        sa.sql.column('name', sa.String),
        sa.sql.column('desc', sa.String),
        sa.sql.column('price', sa.Integer),
    )

    op.bulk_insert(products,
                   [
                       {
                           'id': 1,
                           'name': 'Клавиатура механическая',
                           'desc': 'Цвет: розовый',
                           'price': 15000
                       },
                       {
                           'id': 2,
                           'name': 'Робот-пылесос',
                           'desc': 'Фирма: Xiaomi',
                           'price': 11000
                       },
                       {
                           'id': 3,
                           'name': 'Мобильный телефон',
                           'desc': 'Объем памяти: 256 Гб',
                           'price': 20000
                       },
                       {
                           'id': 4,
                           'name': 'Тапочки домашние',
                           'desc': 'Покрытие: антистатическое',
                           'price': 300
                       },
                   ]
                   )
    
    orders = sa.sql.table(
        'orders',
        sa.sql.column('id', sa.Integer),
        sa.sql.column('password', sa.String),
        sa.sql.column('product_id', sa.Integer),
        sa.sql.column('quantity', sa.Integer),
    )

    op.bulk_insert(orders,
                   [
                       {
                           'id': 1,
                           'password': '8800',
                           'product_id': 3,
                           'quantity': 1
                       },
                       {
                           'id': 2,
                           'password': '5553',
                           'product_id': 4,
                           'quantity': 3
                       },
                       {
                           'id': 3,
                           'password': '5350',
                           'product_id': 2,
                           'quantity': 2
                       },
                   ]
                   )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=4), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orders_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    data_upgrades()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('products')
    # ### end Alembic commands ###
